---

## Docker Install Tasks ##  
- name: Ensure Old Docker Packages are Removed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: Ensure yum-utils Is Present
  yum:
    name: yum-utils
    state: present

- name: Ensure device-mapper-persistent-data Is Present
  yum:
    name: device-mapper-persistent-data
    state: present
  
- name: Ensure lvm2 Is Present
  yum:
    name: lvm2
    state: present

- name: Ensure Docker-CE Repo is Present
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/Docker-CE.repo
    owner: root
    group: root
    mode: 0644

- name: Ensure Docker Engine is Installed
  yum:
    name: docker-ce
    state: "{{ docker_package_state }}"
  